### ISSUE TITLE
NODE_TLS_REJECT_UNAUTHORIZED

### ISSUE THREAD

**Issue by Florian007** [prescottprue/cypress-firebase#13] opened 2019-02-02 12:48 UTC
Hi, thank you for your great work. I'm succesfully authenticating with your library, but get the following error when I'm trying to connect to the realtime firebase database: 

Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

I tried it with this script:

describe("Account Page", () => {
  before(() => {
    cy.login()
    cy.visit("/settings")
 })

it("Should save to Database", () => {
const fakeProject = { some: "data" }
    cy.callRtdb("set", "projects/ABC123", fakeProject)
  })

And already set the enviroment variable for testing in the scripts like:

Cypress.env({
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
})

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"

and in the .bash_profile:
export NODE_TLS_REJECT_UNAUTHORIZED=0 

But I couldn't get it to work. Do you have an clue?
Thank you in advance!

**Comment by prescottprue** [comment] 2019-02-02 19:56
@Florian007 When calling login, a custom token is generated and passed to the window, but it is still up to your application code to take that custom token and login through Firebase.
Make sure you have the following (from [fireadmin as an example](https://github.com/prescottprue/fireadmin/blob/master/src/store/createStore.js#L75-L78))


Add this in your create store file, so that you can initialize from an instance passed to the window (what calling login does)

```js
// Initialize Firebase only if an fbInstance was not passed to the window (tests)
if (!window.fbInstance) {
  firebase.initializeApp(fbConfig)
}
```
Then later on [handle passing of the `window.fbInstance` within your enhancers](https://github.com/prescottprue/fireadmin/blob/master/src/store/createStore.js#L95-L96) (that is if you are not on the next version of react-redux-firebase or the alpha version of redux-firestore, which don't use store enhancers):

```js
const middleware = []

const store = createStore(
  rootReducer,
  initialState,
  compose(
    reactReduxFirebase(window.fbInstance || firebase, combinedConfig),
    reduxFirestore(window.fbInstance || firebase),
    applyMiddleware(...middleware),
  )
)
```

Hopefully that solves it for you since the fbInstance will will be authorized and be passed to your application. Reach out if it doesn't.

I am realizing now though that this isn't documented anywhere in the setup, so I'm going to look into adding that. Thanks for reporting!

**Comment by Florian007** [comment] 2019-02-02 21:05
The complete Error:
Error:       CypressError: cy.exec('npx firebase database:set /projects/ABC123 [object Object] -P XXXXXXXX -y') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 2

Stderr:
(node:79996) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

**Comment by Florian007** [comment] 2019-02-02 21:49
Thank you for your fast answer. But I don't really have a Store. I'm using it only in a cypress Test which I've now updated with your fbInstance Test.

import firebase from "firebase/app"
import "firebase/auth"
import "firebase/database"
import "firebase/firestore"
import { fbConfig } from "../../support/commands"

describe("Firebase RDB Save", () => {
  before(() => {
    // Login using custom token
    cy.login()
    // Go to account page
    cy.visit("/settings")

    // Initialize Firebase only if an fbInstance was not passed to the window (tests)
    if (!window.fbInstance) {
      firebase.initializeApp(fbConfig)
    }
  })

  it("Should save in Rdb", () => {
    const fakeProject = { some: "data" }
    cy.callRtdb("set", "projects/ABC123", fakeProject)
  })
})

And my support/commands.js looks like:

import firebase from "firebase/app"
import "firebase/auth"
import "firebase/database"
import "firebase/firestore"
import { attachCustomCommands } from "cypress-firebase"

export const fbConfig = {
  XXXXXXXXXXX
}

window.fbInstance = firebase.initializeApp(fbConfig)

attachCustomCommands({ Cypress, cy, firebase })

But also with the window.fbInstance Test I get the same error.

Could it have to do with what's mentioned in the cypress error:
Pass {failOnNonZeroExit: false} to ignore exit code failures.

Thank you in advance!

**Comment by Florian007** [comment] 2019-02-02 22:04
If I add the failOnNonZeroExit option to your command in attachCustomCommands.js the error goes away.
`cy.exec(rtdbCommand, { failOnNonZeroExit: false })`

But I then get in cypress on the exec command:
Yielded:     
{stdout: "", stderr: "env: node: No such file or directory", code: 127}

**Comment by Florian007** [comment] 2019-02-02 22:08
The yielded output form above exactly comes after the promise by the "then" like you can see here.

<img width="617" alt="bildschirmfoto 2019-02-02 um 23 07 08" src="https://user-images.githubusercontent.com/1918230/52169876-6efce080-273f-11e9-9076-1b60ce187d99.png">

**Comment by stijnvanlieshout** [comment] 2019-07-28 20:49
I'm facing the same issue:
<img width="860" alt="Screenshot 2019-07-28 at 22 47 21" src="https://user-images.githubusercontent.com/8589586/62012692-e446ec80-b189-11e9-81c1-29a45dfd0158.png">

Did you end up finding a solution?

**Comment by mattvukas** [comment] 2019-08-29 15:45
@stijnvanlieshout I can confirm that I only get this error on Node v12. On Node v10.16.3 (latest LTS version, I no longer get the "Setting the NODE_TLS_REJECT_UNAUTHORIZED..." error.

Otherwise, I am still running into Firestore query permissions issues in our app, even when using the aforementioned `window.fbInstance || firebase` setup when initializing things.

**Comment by prescottprue** [comment] 2020-03-28 07:02
Are folks still experiencing this as an issue with cypress 4.2.0 and cypress-firebase v1.0.0?

v1.0.0 works using tasks and firebase-admin instead of calling through firebase-tools-extra

**Comment by prescottprue** [comment] 2020-04-21 22:12
Closing due to no repro in v1. If anyone is still experiencing this, please reach out

**Closed by prescottprue** 2020-04-21 22:12 UTC
Labels: bug, needs-repro

**Comment by dmytrobasiukqa** [comment] 2022-11-22 11:08
I'm experiencing this. Cypress in ^11.0.1

**Comment by prescottprue** [comment] 2022-11-23 18:29
@dmytrobasiukqa Could you provide steps to replicate or a repo?
