### ISSUE TITLE
Firestore Emulator support

### ISSUE THREAD

**Issue by z4m0** [prescottprue/cypress-firebase#73] opened 2019-11-28 08:34 UTC
Is it possible to add support for Firestore emulator?

**Comment by prescottprue** [comment] 2019-11-28 08:57
The emulator is generally used for testing rules [as mentioned in the firebase docs](https://firebase.google.com/docs/rules/emulator-setup), so not sure exactly how support would look (maybe just to insert data?). That said, if you app is connecting to the emulator, then cypress-firebase should as well I believe.

Did you have a use case or example in mind that isn’t working as you expect?

**Comment by z4m0** [comment] 2019-11-28 19:42
Thank you for answering.

The problem I have is that it is still using the non-local DB (maybe I don't know how to configure it?).

I was looking to run the e2e tests in an emulated environment. Actually developing with the emulator also works well.

Seeing the code it seems to me that some changes may need to go in this repo:
https://github.com/prescottprue/firebase-tools-extra

The changes would be to use @firebase/testing package instead of firebase-admin when wanting to use an emulated environment:

* initializeAdminApp to get the firestore instance.
* clearFirestoreData to clean the DB.

**Comment by prescottprue** [comment] 2019-11-29 05:54
Oh awesome! I was hoping it supported full emulation, but wasn’t sure based on the docs. Haven’t used it yet, but yet I will look into making the making the changes to the testing package as you mentioned.

This will be amazing for testing in mine and my teams current apps, so thanks for clarifying

**Comment by prescottprue** [comment] 2019-11-29 09:49
I also realized that It appears there [is logic in firebase-tools-extra for supporting this](https://github.com/prescottprue/firebase-tools-extra/blob/master/src/utils.ts#L259). Just need to write up a working example

**Comment by diginikkari** [comment] 2019-11-29 13:32
It would be create if we could use firebase-testing also with cypress. I'm using it with jest to write integration test to cloud functions. It's great because it makes it possible to run tests in parallel with full isolation between tests. 

firebase-testing doesn't yet support authentication, so that is something to figure out also.

Here is article about it: [Jest testing firebase functions with emulator-suite](https://medium.com/@timo.santi/jest-testing-firebase-functions-with-emulator-suite-409907f31f39?source=friends_link&sk=91377b96f578e3d42f85a9631f69123a).

**Comment by prescottprue** [comment] 2019-12-05 10:09
I was able to get `cy.callFirestore` calling to the emulator with `set` and `update` when including the following within the initialization section of my application:

```js
const firebaseConfig = {
  // Your original config
}
if (window.Cypress) {
  config.firebase.projectId = 'test'
}
// Initialize Firebase instance
firebase.initializeApp(config.firebase)

if (window.Cypress) {
  firebase.firestore().settings({
    host: 'localhost:8080',
    ssl: false
  })
}
```

Then when booting up cypress, I pass the emulator environment variable (which is mentioned when starting up the emulator):
```bash
FIRESTORE_EMULATOR_HOST=localhost:8080 cypress open
```

All of that said, I am [improving the logic within firebase-tools-extra](https://github.com/prescottprue/firebase-tools-extra/pull/13) to dynamically load `projectId` from the environment so it can match the project and doesn't need to be passed as shown above.

Something else to note is that this will methodology will only really work for the listed Firestore commands for now (not `delete` and nothing on the RTDB side), since the other commands are piped directly to `firebase-tools`. Going to have to dive deeper on their code to see if that can be overridden with environment variables being passed, if not we will have to build out `firebase-tools-extra` to handle all of the RTDB interactions as well.

Going to also work on documenting all of this, and maybe even write up a medium article outline the full flow. Thanks to all for your input, I'm open to PRs for any of this stuff if anyone feels like it - both of these libs are pretty young, so there isn't too much to worry about breaking.

**Comment by prescottprue** [comment] 2019-12-05 11:13
Yeah, as expected, it appears that firebase-tools database commands do not support the emulator ([as seen in the database push](https://github.com/firebase/firebase-tools/blob/master/src/commands/database-push.js#L47).

I also tried with`firestore:delete`, by overriding the based URL like so: ` FIRESTORE_URL=http://localhost:8080 firebase firestore:delete /users/2Sos5CpSLifCcPTyrTn0G2xmsiR2`, but that didn't work either. I reached out to Firebase about adding this as a feature, but in the meantime it seems like we will need to add this functionality to firebase-tools-extra as mentioned. Thinking that I will get v0.3.0 out with the fixes for projectId then add that functionality in another upcoming version since it will mean some changes to cypress-firebase as well.

**Comment by prescottprue** [comment] 2019-12-07 07:01
I got a response to the feature request that I made to Firebase for adding this to firebase-tools - they said they like the idea, but are not sure on a timeline yet. I'll keep an eye out for the issue they said they would make to track this, and link it here.

**Comment by prescottprue** [comment] 2019-12-07 07:51
Just released [v0.5.1](https://github.com/prescottprue/cypress-firebase/releases/tag/v0.5.1) with the improved logic which loads project name dynamically. Going to start working on support for the `delete` within Firestore (since only `set` and `update` will work for now) and the RTDB methods since we don't yet have a timeline of when it will be added to firebase-tools

**Comment by amkoehler** [comment] 2020-01-13 22:30
Got this working great. I'm having a related issue but I think it is an underlying cypress problem. Has anyone else had issues connecting to the firestore emulator from cypress while running in the browser? For some reason my cypress tests are failing to connect to my emulator. I can connect to the emulator just fine when visiting my dev server outside of cypress.

related SO issue from another user: https://stackoverflow.com/questions/59336720/cant-use-cypress-to-test-app-using-using-firestore-local-emulator

**Comment by Corchoneitor** [comment] 2020-01-31 20:20
> Got this working great. I'm having a related issue but I think it is an underlying cypress problem. Has anyone else had issues connecting to the firestore emulator from cypress while running in the browser? For some reason my cypress tests are failing to connect to my emulator. I can connect to the emulator just fine when visiting my dev server outside of cypress.
> 
> related SO issue from another user: https://stackoverflow.com/questions/59336720/cant-use-cypress-to-test-app-using-using-firestore-local-emulator

Same problem here. Did you find a solution?

**Comment by prescottprue** [comment] 2020-01-31 22:20
I was able to communicate with the emulator through cypress, not sure why I didn't hit that issue. I'll look to try to replicate

**Comment by prescottprue** [comment] 2020-02-03 18:43
@amkoehler What does your app initialization logic look like? Do you load the firebase instance created within Cypress (and attach it to the window within your cypress logic?)

**Comment by prescottprue** [comment] 2020-02-06 18:21
More full support has been added for both RTDB and Firestore emulators.

One issues I have come upon though is a failure to be able to connect to the Firestore emulator within Cypress - I created this issue in the Cypress repo with reproduction steps: https://github.com/cypress-io/cypress/issues/6350

**Comment by prescottprue** [comment] 2020-02-20 18:30
Passing `experimentalForceLongPolling: true` to Firestore settings allows the Firestore emulator to work within Cypress. Closing since this has been noted in the README and there is full emulator support for `callRtdb` and `callFirestore`

**Closed** 2020-02-20 18:48 UTC
Labels: enhancement
